import { ReactNode } from "react";
import { Inter } from "next/font/google";

import ThemeRegistry from "./themeRegister";
import GlobalComponent from "./globalComponent";
import { Providers } from "@/util/lib/redux/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "惠惠",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ThemeRegistry options={{ key: "mui" }}>
            <GlobalComponent>{children}</GlobalComponent>
          </ThemeRegistry>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
